image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update
  - apt-get install -y python-dev libffi-dev build-essential python2.7
  - pip install git+https://gitlab.com/dataroots-public/mlmonkey.git
  - pip install -r requirements.txt

test:
  script:
    - make test
