image: continuumio/miniconda3:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update
  - apt-get install -y build-essential python2.7
  - pip install -r requirements.txt
  - pip install mlmonkey/.

test:
  script:
    - make test
