version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
    - "5000:5000"

  jupyter:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - ./:/home/jovyan/work