version: '3'

services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
    - "5000:5000"

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    ports:
    - "8888:8888"
    volumes:
    - ./:/home/jovyan/work