version: '3'

services:

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    ports:
    - "9090:9090"

  jupyter:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.jupyter
    ports:
    - "8888:8888"
    volumes:
    - ./:/workspace/project_mount