[default]
DATA_RAW = "./data/raw/"
DYNACONF_DATA_TRANSFORMED = "./data/transformed/"
DYNACONF_DATA_STAGING = "./data/staging/"
DYNACONF_PREDICTIONS = "./data/predictions/"

DYNACONF_ETL_DIR = "./src/etl"

DYNACONF_MODEL_DIR = "./models"
DYNACONF_MODEL_METADATA_DIR = "./models/metadata"

DYNACONF_FLASK_ENDPOINT_HOST = "0.0.0.0"
DYNACONF_FLASK_ENDPOINT_PORT = 5000

key = "value"
a_boolean = false
number = 1234
a_float = 56.8

[development]

[staging]

[testing]

[production]

