openapi: 3.0.0
info:
  description: API for serving model predictions.
  version: 1.0.0
  title: Model Api
paths:
  /predict:
    post:
      summary: Calculate predictions for provided observations.
      tags:
        - predictions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                features:
                  oneOf:
                    - type: array
                      items:
                        oneOf:
                          - type: string
                          - type: integer
                          - type: number
                          - type: boolean
                    - type: array
                      items:
                        type: array
                        items:
                          oneOf:
                            - type: string
                            - type: integer
                            - type: number
                            - type: boolean
              required:
                - features
            example:
              features:
                - - 2
                  - 3.1
                - - 2.4
                  - 5
      responses:
        '200':
          description: Calculated predictions
          content:
            application/json:
              schema:
                type: object
                properties:
                  release:
                    type: object
                    properties:
                      model_id:
                        type: string
                        description: Unique model identifier
                      git_commit:
                        type: string
                        description: Id of git commit, identifying model code
                  result:
                    type: array
                    items:
                      type: number
                    description: Predictions, probabilities or predicted values
                  timing:
                    type: number
                    description: Elapsed time in seconds
                example:
                  release:
                    model_id: 7981eb836817dbb4ef1fb1e70bafa10a924b99e4
                    git_commit: e4a77795d26b91d2b3670ceabc8d8d0322fc58d8
                  result: [23.4903, 43.05]
                  timing: 0.54
